AirlinesWeb/Controllers/FlightController.cs
using Airlines.Persistence.Basic.Entities;
using Airlines.Persistence.Basic.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AirlinesWeb.Controllers;
#pragma warning disable IDE0290 // Use primary constructor
#pragma warning disable IDE0060 // Remove unused parameter
#pragma warning disable IDE0022 // Use expression body for method
#pragma warning disable IDE0021 // Use expression body for constructor
public class FlightController : Controller
{
    private readonly IFlightRepository _flightRepository;

    public FlightController(IFlightRepository repository)
    {
        _flightRepository = repository;
    }

    // GET: FlightController
    public ActionResult Index(string searchTerm, string flightNumber, string fromAirportId, string toAirportId)
    {
        var flights = _flightRepository.GetAllFlights();

        if (!string.IsNullOrEmpty(searchTerm))
        {
            flights = flights.Where(f => f.FlightNumber.Contains(searchTerm)).ToList();
        }

        if (!string.IsNullOrEmpty(flightNumber))
        {
            flights = flights.Where(f => f.FlightNumber.Contains(flightNumber)).ToList();
        }

        if (!string.IsNullOrEmpty(fromAirportId))
        {
            flights = flights.Where(f => f.FromAirportId.ToString().Contains(fromAirportId)).ToList();
        }

        if (!string.IsNullOrEmpty(toAirportId))
        {
            flights = flights.Where(f => f.ToAirportId.ToString().Contains(toAirportId)).ToList();
        }

        ViewBag.CurrentFilter = searchTerm;

        return View(flights);
    }

    // GET: FlightController/Details/5
    public ActionResult Details(int id)
    {
        return View();
    }

    // GET: FlightController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: FlightController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult CreateNewFlight(Flight flight)
    {
        if (flight.Arrival < DateTime.Now)
        {
            ModelState.AddModelError("Arrival", "The date should be later than now");
        }

        if (flight.Departure > flight.Arrival)
        {
            ModelState.AddModelError("Departure", "The date should be later than now");
        }

        if (flight.FlightNumber.Length > 6 && !string.IsNullOrEmpty(flight.FlightNumber))
        {
            ModelState.AddModelError("FlightNumber", "Number must be lower than 6 chars");
        }

        if (ModelState.IsValid)
        {
            _flightRepository.CreateFlight(flight);
            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: FlightController/Edit/5
    public ActionResult Edit(int id)
    {
        return View();
    }

    // POST: FlightController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    // GET: FlightController/Delete/5
    public ActionResult Delete(int id)
    {
        return View();
    }

    // POST: FlightController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}

AirlinesWeb/Views/Flight/Index.cshtml
@model IEnumerable<Airlines.Persistence.Basic.Entities.Flight>

@{
	ViewData["Title"] = "Index";
}

<h1>Flights</h1>
<div id="table-and-filter">
	<form asp-controller="Flight" asp-action="Index" method="get">
		<input type="text" name="searchTerm" placeholder="Search by Flight Number" value="@ViewBag.CurrentFilter">
		<input type="submit" value="Search">
	</form>
	<form asp-controller="Flight" asp-action="Index" method="get">
		<label for="flightNumber">Flight Number:</label>
		<input type="text" id="flightNumber" name="flightNumber">
		<label for="fromAirportId">From Airport ID:</label>
		<input type="text" id="fromAirportId" name="fromAirportId">
		<label for="toAirportId">To Airport ID:</label>
		<input type="text" id="toAirportId" name="toAirportId">
		<input type="submit" value="Filter">
	</form>
	<div class="table-form">
		<table id="flightsTable">
			<thead>
				<tr>
					<th>@Html.DisplayNameFor(model => model.FlightNumber)</th>
					<th>@Html.DisplayNameFor(model => model.FromAirportId)</th>
					<th>@Html.DisplayNameFor(model => model.ToAirportId)</th>
					<th>@Html.DisplayNameFor(model => model.Departure)</th>
					<th>@Html.DisplayNameFor(model => model.Arrival)</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.FlightNumber)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.FromAirportId)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.ToAirportId)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Departure)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Arrival)
						</td>
					</tr>
				}
			</tbody>
		</table>
	<button id="scrollButton">Scroll to First Element</button>
	</div>
</div>
<div id="ThreeItemsDiv">
	<table id="ThreeItemsTable">
		<thead>
			<tr>
				<th>@Html.DisplayNameFor(model => model.FlightNumber)</th>
				<th>@Html.DisplayNameFor(model => model.FromAirportId)</th>
				<th>@Html.DisplayNameFor(model => model.ToAirportId)</th>
				<th>@Html.DisplayNameFor(model => model.Departure)</th>
				<th>@Html.DisplayNameFor(model => model.Arrival)</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Take(3))
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.FlightNumber)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.FromAirportId)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.ToAirportId)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Departure)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.Arrival)
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>
<p onclick="showTable()" id="show-table" class="create-new-button">
	<a>Show More</a>
</p>
<p onclick="showForm()" id="show-form" class="create-new-button">
	<a>Show Form</a>
</p>
<p id="submit-label" class="submit-label">Add New Flight</p>
<div id="submit-form" class="submit-form">
	<form asp-action="CreateNewFlight" method="post">
		<div class="submit-element">
			<div class="form-group">
				<label for="FlightNumber" class="control-label">FlightNumber</label>
				<input id="FlightNumber" type="text" name="FlightNumber" class="form-control" oninput="checkIsValid()" />
				<span class="error">Flight number must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="FromAirportId" class="control-label">FromAirportId</label>
				<input type="number" name="FromAirportId" class="form-control" oninput="checkIsValid()" />
				<span class="error">FromAirportId must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="ToAirportId" class="control-label">ToAirportId</label>
				<input type="number" name="ToAirportId" class="form-control" oninput="checkIsValid()" />
				<span class="error">ToAirportId must not be empty!</span>
			</div>
		</div>
		<div class="departure-and-arrival">
			<div class="departure-and-arrival-element">
				<div class="form-group">
					<label for="Departure" class="control-label">Departure</label>
					<input type="datetime-local" name="Departure" class="form-control" oninput="checkIsValid()" />
					<span class="error">Departure must not be empty!</span>
				</div>
			</div>
			<div class="departure-and-arrival-element">
				<div class="form-group">
					<label for="Arrival" class="control-label">Arrival</label>
					<input type="datetime-local" name="Arrival" class="form-control" oninput="checkIsValid()" />
					<span class="error">Arrival must not be empty!</span>
				</div>
			</div>
		</div>
		<div class="form-group">
			<input asp-controller="Flight" asp-action="CreateNewFlight" class="submit-button" type="submit" value="Create" class="btn btn-primary" />
		</div>
	</form>
</div>
@section Scripts {
	<script src="~/js/validation.js"></script>
	<script src="~/js/site.js"></script>
}