AirlinesWeb/Controllers/AirportController.cs
using Airlines.Persistence.Basic.Entities;
using Airlines.Persistence.Basic.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AirlinesWeb.Controllers;
#pragma warning disable IDE0290 // Use primary constructor
#pragma warning disable IDE0060 // Remove unused parameter
#pragma warning disable IDE0022 // Use expression body for method
#pragma warning disable IDE0021 // Use expression body for constructor
public class AirportController : Controller
{
    private readonly IAirportRepository _airportRepository;

    public AirportController(IAirportRepository airportRepository)
    {
        _airportRepository = airportRepository;
    }

    // GET: AirportController
    public ActionResult Index(string searchTerm, string country, string city, string code, string runwayCount)
    {
        var airports = _airportRepository.GetAllAirports();

        if (!string.IsNullOrEmpty(searchTerm))
        {
            airports = airports.Where(f => f.AirportName.Contains(searchTerm)).ToList();
        }

        if (!string.IsNullOrEmpty(country))
        {
            airports = airports.Where(f => f.Country.Contains(country)).ToList();
        }

        if (!string.IsNullOrEmpty(city))
        {
            airports = airports.Where(f => f.City.ToString().Contains(city)).ToList();
        }

        if (!string.IsNullOrEmpty(code))
        {
            airports = airports.Where(f => f.Code.ToString().Contains(code)).ToList();
        }

        if (!string.IsNullOrEmpty(runwayCount))
        {
            airports = airports.Where(a => a.RunwayCount == int.Parse(runwayCount)).ToList();
        }

        ViewBag.CurrentFilter = searchTerm;

        return View(airports);
    }

    // GET: AirportController/Details/5
    public ActionResult Details(int id)
    {
        return View();
    }

    // GET: AirportController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: AirportController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult CreateNewAirport(Airport airport)
    {
        if (airport.Founded < new DateOnly(2024, 1, 1))
        {
            ModelState.AddModelError("Founded", "The date should be earlier than now");
        }

        if (!string.IsNullOrEmpty(airport.AirportName))
        {
            ModelState.AddModelError("AirportName", "Name must be filled");
        }

        if (!string.IsNullOrEmpty(airport.City))
        {
            ModelState.AddModelError("City", "City must be filled");
        }

        if (!string.IsNullOrEmpty(airport.Country))
        {
            ModelState.AddModelError("Country", "Country must be filled");
        }

        if (airport.RunwayCount > 0)
        {
            ModelState.AddModelError("RunwayCount", "Runways must be positive number");
        }

        if (airport.Code.Length == 3 && !string.IsNullOrEmpty(airport.AirportName) && !airport.Code.All(char.IsDigit))
        {
            ModelState.AddModelError("Code", "Code must be 3 char lenght");
        }

        if (ModelState.IsValid)
        {
            _airportRepository.CreateAirport(airport);

            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: AirportController/Edit/5
    public ActionResult Edit(int id)
    {
        return View();
    }

    // POST: AirportController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    // GET: AirportController/Delete/5
    public ActionResult Delete(int id)
    {
        return View();
    }

    // POST: AirportController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }
}

AirlinesWeb/Views/Airport/Index.cshtml
@model IEnumerable<Airlines.Persistence.Basic.Entities.Airport>

@{
	ViewData["Title"] = "Airports";
}

<h1>Airports</h1>
<div id="table-and-filter">
	<form asp-controller="Airport" asp-action="Index" method="get">
		<input type="text" name="searchTerm" placeholder="Search by Airport name" value="@ViewBag.CurrentFilter">
		<input type="submit" value="Search">
	</form>
	<form asp-controller="Airport" asp-action="Index" method="get">
		<label for="airportName">Airport name:</label>
		<input type="text" id="airportName" name="airportName">
		<label for="country">Country:</label>
		<input type="text" id="country" name="country">
		<label for="city">City:</label>
		<input type="text" id="city" name="city">
		<label for="code">Code:</label>
		<input type="text" id="code" name="code">
		<label for="runwayCount">Runways:</label>
		<input type="text" id="runwayCount" name="runwayCount">
		<input type="submit" value="Filter">
	</form>
	<div class="table-form">
		<table class="table">
			<thead>
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.AirportName)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Country)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.City)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Code)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.RunwayCount)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Founded)
					</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.AirportName)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Country)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.City)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Code)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.RunwayCount)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Founded)
						</td>
					</tr>
				}
			</tbody>
		</table>
		<button id="scrollButton">Scroll to First Element</button>
	</div>
</div>
<div id="ThreeItemsDiv">
	<table id="ThreeItemsTable" class="table">
		<thead>
			<tr>
				<th>@Html.DisplayNameFor(model => model.AirportName)</th>
				<th>@Html.DisplayNameFor(model => model.Country)</th>
				<th>@Html.DisplayNameFor(model => model.City)</th>
				<th>@Html.DisplayNameFor(model => model.Code)</th>
				<th>@Html.DisplayNameFor(model => model.RunwayCount)</th>
				<th>@Html.DisplayNameFor(model => model.Founded)</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Take(3))
			{
				<tr>
					<td>@Html.DisplayFor(modelItem => item.AirportName)</td>
					<td>@Html.DisplayFor(modelItem => item.Country)</td>
					<td>@Html.DisplayFor(modelItem => item.City)</td>
					<td>@Html.DisplayFor(modelItem => item.Code)</td>
					<td>@Html.DisplayFor(modelItem => item.RunwayCount)</td>
					<td>@Html.DisplayFor(modelItem => item.Founded)</td>
				</tr>
			}
		</tbody>
	</table>
</div>
<p onclick="showTable()" id="show-table" class="create-new-button">
	<a>Show More</a>
</p>
<p onclick="showForm()" id="show-form" class="create-new-button">
	<a>Show Form</a>
</p>
<p id="submit-label" class="submit-label">Add New Airport</p>
<div id="submit-form" class="submit-form">
	<form asp-action="CreateNewAirport" method="post">
		<div class="submit-element">
			<div class="form-group">
				<label for="AirportName" class="control-label">AirportName</label>
				<input type="text" name="AirportName" class="form-control" oninput="checkIsValid()" />
				<span class="error">Airport name must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="Country" class="control-label">Country</label>
				<input type="text" name="Country" class="form-control" oninput="checkIsValid()" />
				<span class="error">Country must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="City" class="control-label">City</label>
				<input type="text" name="City" class="form-control" oninput="checkIsValid()" />
				<span class="error">City must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="Code" class="control-label">Code</label>
				<input type="text" name="Code" class="form-control" oninput="checkIsValid()" />
				<span class="error">Code must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="RunwayCount" class="control-label">RunwayCount</label>
				<input type="number" name="RunwayCount" class="form-control" oninput="checkIsValid()" />
				<span class="error">Runway count must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="Founded" class="control-label">Founded</label>
				<input type="datetime-local" name="Founded" class="form-control" oninput="checkIsValid()" />
				<span class="error">Founded must not be empty!</span>
			</div>
		</div>
		<div class="form-group">
			<input asp-controller="Airport" asp-action="CreateNewAirport" class="submit-button" type="submit" value="Create" class="btn btn-primary" />
		</div>
	</form>
</div>
@section Scripts {
	<script src="~/js/site.js"></script>
	<script src="~/js/validation.js"></script>
}