AirlinesWeb/Controllers/AirlineController.cs
using Airlines.Persistence.Basic.Entities;
using Airlines.Persistence.Basic.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace AirlinesWeb.Controllers;
#pragma warning disable IDE0022 // Use expression body for method
#pragma warning disable IDE0021 // Use expression body for constructor
#pragma warning disable IDE0290 // Use primary constructor
#pragma warning disable IDE0060 // Remove unused parameter
public class AirlineController : Controller
{
    private readonly IAirlineRepository _airlineRepository;

    public AirlineController(IAirlineRepository repository)
    {
        _airlineRepository = repository;
    }

    // GET: AirlineController
    public ActionResult Index(string searchTerm, string airlineName, string fleetSize)
    {
        var airlines = _airlineRepository.GetAllAirlines();

        if (!string.IsNullOrEmpty(searchTerm))
        {
            airlines = airlines.Where(f => f.AirlineName.Contains(searchTerm)).ToList();
        }

        if (!string.IsNullOrEmpty(airlineName))
        {
            airlines = airlines.Where(f => f.AirlineName.Contains(airlineName)).ToList();
        }

        if (!string.IsNullOrEmpty(fleetSize))
        {
            airlines = airlines.Where(f => f.FleetSize.ToString().Contains(fleetSize)).ToList();
        }

        ViewBag.CurrentFilter = searchTerm;

        return View(airlines);
    }

    // GET: AirlineController/Details/5
    public ActionResult Details(int id)
    {
        return View();
    }

    // GET: AirlineController/Create
    public ActionResult Create()
    {
        return View();
    }

    // POST: AirlineController/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult CreateNewAirline(Airline airline)
    {
        if (airline.Founded < new DateOnly(2024, 1, 1))
        {
            ModelState.AddModelError("Founded", "The date should be earlier than now");
        }

        if (airline.AirlineName.Length > 6 && !string.IsNullOrEmpty(airline.AirlineName))
        {
            ModelState.AddModelError("Name", "Name must be no longer than 6 and must be filled");
        }

        if (airline.FleetSize > 0)
        {
            ModelState.AddModelError("FleetSize", "Fleet size must be greater than 0");
        }

        if (airline.AirlineDescription.Length > 50)
        {
            ModelState.AddModelError("AirlineDescription", "Description must be longer than 50 chars");
        }

        if (ModelState.IsValid)
        {
            _airlineRepository.CreateAirline(airline);

            return RedirectToAction(nameof(Index));
        }

        return RedirectToAction(nameof(Index));
    }

    // GET: AirlineController/Edit/5
    public ActionResult Edit(int id)
    {
        return View();
    }

    // POST: AirlineController/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit(int id, IFormCollection collection)
    {
        try
        {
            return RedirectToAction(nameof(Index));
        }
        catch
        {
            return View();
        }
    }

    // GET: AirlineController/Delete/5
    public ActionResult Delete(int id)
    {
        return View();
    }

    // POST: AirlineController/Delete/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Delete(int id, IFormCollection collection)
    {
        _airlineRepository.RemoveAirlineById(id);

        return RedirectToAction(nameof(Index));
    }
}

AirlinesWeb/Views/Airline/Index.cshtml
@model IEnumerable<Airlines.Persistence.Basic.Entities.Airline>

@{
	ViewData["Title"] = "Airlines";
}

<h1>Airlines</h1>
<div id="table-and-filter">
	<form asp-controller="Airline" asp-action="Index" method="get">
		<input type="text" name="searchTerm" placeholder="Search by Airline name" value="@ViewBag.CurrentFilter">
		<input type="submit" value="Search">
	</form>
	<form asp-controller="Airline" asp-action="Index" method="get">
		<label for="airlineName">Airline name:</label>
		<input type="text" id="airlineName" name="airlineName">
		<label for="fleetSize">Fleet size:</label>
		<input type="text" id="fleetSize" name="fleetSize">
		<input type="submit" value="Filter">
	</form>
	<div class="table-form">
		<table class="table">
			<thead>
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.AirlineName)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.FleetSize)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.AirlineDescription)
					</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.AirlineName)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.FleetSize)
						</td>
						<td class="description">
							@Html.DisplayFor(modelItem => item.AirlineDescription)
						</td>
					</tr>
				}
			</tbody>
		</table>
		<button id="scrollButton">Scroll to First Element</button>
	</div>
</div>
<div id="ThreeItemsDiv">
	<table id="ThreeItemsTable" class="table">
		<thead>
			<tr>
				<th>@Html.DisplayNameFor(model => model.AirlineName)</th>
				<th>@Html.DisplayNameFor(model => model.FleetSize)</th>
				<th>@Html.DisplayNameFor(model => model.AirlineDescription)</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var item in Model.Take(3))
			{
				<tr>
					<td>@Html.DisplayFor(modelItem => item.AirlineName)</td>
					<td>@Html.DisplayFor(modelItem => item.FleetSize)</td>
					<td class="description">@Html.DisplayFor(modelItem => item.AirlineDescription)</td>
				</tr>
			}
		</tbody>
	</table>
</div>
<p onclick="showTable()" id="show-table" class="create-new-button">
	<a>Show More</a>
</p>
<p onclick="showForm()" id="show-form" class="create-new-button">
	<a>Show Form</a>
</p>
<p id="submit-label" class="submit-label">Add New Airline</p>
<div id="submit-form" class="submit-form">
	<form asp-action="CreateNewAirline" method="post">
		<div class="submit-element">
			<div class="form-group">
				<label for="AirlineName" class="control-label">AirlineName</label>
				<input type="text" name="AirlineName" class="form-control" oninput="checkIsValid()" />
				<span class="error">Airline name must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="FleetSize" class="control-label">FleetSize</label>
				<input type="number" name="FleetSize" class="form-control" oninput="checkIsValid()" />
				<span class="error">Fleet size must not be empty!</span>
			</div>
		</div>
		<div class="submit-element">
			<div class="form-group">
				<label for="AirlineDescription" class="control-label">AirlineDescription</label>
				<input type="text" name="AirlineDescription" class="form-control" oninput="checkIsValid()" />
				<span class="error">Airline description must not be empty!</span>
			</div>
		</div>
		<div class="form-group">
			<input asp-controller="Airline" asp-action="CreateNewAirline" class="submit-button" type="submit" value="Create" class="btn btn-primary" />
		</div>
	</form>
</div>
@section Scripts {
	<script src="~/js/validation.js"></script>
	<script src="~/js/site.js"></script>
}